                                                    ASSIGNMENT 2 (NUMPY)
                    NAME: VANSHAJ SINGLA               ROLL NO: 102003346                         GROUP: CO14

In [4]:
import numpy as np
a=np.ones(10,int)*5
a

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [6]:
arr=np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [7]:
arr2=np.arange(10,51,2)
arr2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [17]:
mat=np.arange(0,9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
np.random.randn(25)

array([ 0.82959575, -0.51275406, -0.362019  ,  2.092041  , -1.15098818,
        0.8028238 ,  0.14630584, -1.63113098, -1.89753441,  2.09362736,
       -0.73498901, -0.64715956, -0.72293721,  0.25614088, -0.01900006,
       -0.18062868, -0.77025931,  0.98285135, -0.16893462,  0.05743531,
        1.70792748,  1.39001825,  0.72974257, -1.09638931, -0.79409394])

In [14]:
arr2=np.arange(0,1.01,0.01)
arr2

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ,
       0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21,
       0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32,
       0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43,
       0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54,
       0.55, 0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65,
       0.66, 0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76,
       0.77, 0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87,
       0.88, 0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98,
       0.99, 1.  ])

In [15]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [22]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [42]:
print(mat[2:,1:])
print(mat[0:3,1:2])
print('sum=',mat.sum())
print('sum of col.=',mat.sum(axis=0))
print('sum of rows=',mat.sum(axis=1))

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]
[[ 2]
 [ 7]
 [12]]
sum= 325
sum of col.= [55 60 65 70 75]
sum of rows= [ 15  40  65  90 115]
